import type { NextPage } from 'next'
import React from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MetaData from '../components/metaDatas/metas'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <MetaData />
      <main>
        <h1>
          AV System Geo
        </h1>
        <p>
          Generated by AV System Geo
        </p>
        <div>
          <a href="https://www.avsystem.com/">AVG
            <Image src="/avsystem.png" alt="AV System" width={200} height={200} />
          </a>
          <a href="https://www.geo.avsystem.com/">Geo
            <Image src="/geo.png" alt="Geo" width={200} height={200} />
          </a>
          </div>
        </main>
    </div>
  )
}

export default Home
