import type { NextPage } from 'next'
import React from 'react'
import Image from 'next/image'
import MetaData from '../components/metaDatas/metas'
import { Container, Typography } from '@mui/material'

const Home: NextPage = () => {
  return (
    <div>
      <MetaData />
      <Container>
        <Typography variant="h1">
          AV System Geo
        </Typography>
        <Typography variant="h4">
          Generated by AV System Geo
        </Typography>
        <div>
          <a href="https://www.avsystem.com/">AVG
            <Image src="/avsystem.png" alt="AV System" width={200} height={200} />
          </a>
          <a href="https://www.geo.avsystem.com/">Geo
            <Image src="/geo.png" alt="Geo" width={200} height={200} />
          </a>
        </div>
        </Container>
    </div>
  )
}

export default Home
