import React from 'react'
import Head from 'next/head'

type IProps = {
  title?: string;
  children?: React.ReactNode;
}

export default function MetaData (props:IProps) {
  return (
    <Head>
        <title>{props.title || 'AV System Geo'}</title>
        <meta name="description" content="Generated by AV System Geo" />
        <link rel="icon" href="/favicon.png" />
    </Head>
  )
}
